MySimbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import home_all.urls as home_all
import list_pendaftar.urls as list_pendaftar
import login.urls as login
import register_akun.urls as register_akun
import register_beasiswa.urls as register_beasiswa
import register_sb.urls as register_sb
import register_sbaktif.urls as register_sbaktif

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=True), name = 'index'),

    #rafif
    url(r'^login/', include(login,namespace='login')),
    url(r'^register_akun/', include(register_akun,namespace='register_akun')),

    #rehan
    url(r'^register_sb/', include(register_sb,namespace='register_sb')),
    url(r'^register_sbaktif/', include(register_sbaktif,namespace='register_sbaktif')),
    url(r'^home/', include(home_all,namespace='home')),

    #prima
    url(r'^list_pendaftar/', include(list_pendaftar,namespace='list_pendaftar')),
    url(r'^register_beasiswa/', include(register_beasiswa,namespace='register_beasiswa'))
]

home_all/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from .views import index_all, index_donatur, deskripsi_beasiswa

#url for app
urlpatterns = [
    url(r'^$', index_all, name='index_all'),
    url(r'^donatur/', index_donatur, name='index_donatur'),
    url(r'^deskripsi/(?P<kode>\w+)/$', deskripsi_beasiswa, name='deskripsi_beasiswa'),
]

login/urls.py
from django.conf.urls import url
from .views import index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

home_all/models.py
from django.db import models

# Create your models here.

home_all/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db import connection

# Create your views here.
def index_all(request):
    response = {}
    html = "list_beasiswa_all_user.html"

    #query semua skema beasiswa aktif buat ditampilin di dashboard yang semua orang bisa liat
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM SKEMA_BEASISWA_AKTIF ORDER BY (kode_skema_beasiswa,no_urut) ASC")
    response['beasiswa'] = cursor.fetchall()
    cursor.close()

    return render(request, html, response)

def index_donatur(request):

    # dummy account, nunggu fitur login logout dulu
    username_donatur = 'bcade68'
    nomor_identitas_donatur = '444-78-5633'

    response = {}
    html = "lihatbeasiswa_donatur.html"

    #query semua skema beasiswa aktif yang dibuat sama orang yang lagi login
    cursor1 = connection.cursor()
    cursor1.execute("SELECT * FROM SKEMA_BEASISWA_AKTIF SA, SKEMA_BEASISWA S, DONATUR D WHERE SA.kode_skema_beasiswa=S.kode AND D.nomor_identitas=S.nomor_identitas_donatur AND D.username='" + username_donatur + "' ORDER BY (kode_skema_beasiswa,no_urut) ASC")
    response['beasiswa'] = cursor1.fetchall()
    cursor1.close()
    
    #query semua skema beasiswa (paket) yang dibuat sama orang yang lagi login
    cursor2 = connection.cursor()
    cursor2.execute("SELECT kode, nama, count(no_urut) FROM SKEMA_BEASISWA S LEFT JOIN SKEMA_BEASISWA_AKTIF SA ON S.kode=SA.kode_skema_beasiswa where S.nomor_identitas_donatur='%s' GROUP BY (kode,nama)" % nomor_identitas_donatur)
    response['skema'] = cursor2.fetchall()
    cursor2.close()
    
    return render(request, html, response)
    
def deskripsi_beasiswa(request, kode):
    response = {}
    html = "deskripsibeasiswa.html"

    c = connection.cursor()
    c.execute("SELECT * FROM SKEMA_BEASISWA WHERE kode=%s" % kode)
    response['info'] = c.fetchall()

    return render(request, html, response)

home_all/templates/partials/header.html
<style>
        body {
          background: #ecf0f1;  /* fallback for old browsers */
          font-size: 20px;
          margin-bottom: 100px;
        }
        ul.nav.navbar-nav .dropdown.open .dropdown-toggle{
          background-color: #206578;
        }

        nav{
          font-family: 'gilroy-extrabold';
		
		 
        }

        @font-face {
          font-family: 'gilroy-light';
          src: url('gilroy-light.otf') format('opentype');
          font-weight: bold;
          font-style: bold;
        }

        @font-face {
          font-family: 'gilroy-extrabold';
          src: url('gilroy-extrabold.otf') format('opentype');
          font-weight: bold;
          font-style: bold;
        }

        .dropdown-menu > li > a:hover {
          background-color: #398DA3;
        }
        .navbar-nav>li>a {
          color: #444 !important;
          background: transparent;
          margin-bottom: 6px;
          top: 6px;
        }
        li.some-text {
          padding:12px 15px 5px 25px;
          font-size: 15px;
		  
        }
        .navbar {
          background: #fff;  /* fallback for old browsers */
          box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);
          -moz-box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);
          -webkit-box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);
			
          border-radius: none;
          border: none;
          padding-bottom:50px;
		  
        }
        .header {
          padding: 3px 10px;
		  
        }
        li.button-login a{
          top: 2px;
        }
        .navbar-nav >li> a:hover {
          color: #444 !important;
          background: none;
        }
        .navbar-nav .dropdown li.active a {
          color: default;
          background-color: default;
          border-bottom: none;
        }
        .navbar-nav li.active a {
          color: #444 !important;
          background-color: transparent !important;
          border-bottom: 3px solid #ecf0f1;
        }
        .navbar-default .navbar-toggle .icon-bar {
          background-color: #444 !important;
        }
        .navbar-toggle{
          background: transparent;
          border: none;
          position: right;
        }
        .navbar-toggle:focus, .navbar-toggle:hover{
          background: rgba(236, 240, 241, 0.1) !important;
        }
        .logo1 {
          width: 150px;
        }
        li.some-text a {
          color: #77c9d4 !important;
          margin-bottom: 0;
          top: 0;
        }
        li.some-text {
          line-height: auto;
        }
        .btn-login {
          background: #FDD947;
          border-radius: 30px;
          color: #444;
          font-size: 20px;
          padding: 2px 30px;
          -webkit-transition-duration: 0.5s; /* Safari */
          transition-duration: 0.5s;
        }

        .btn-submit {
          display: block;
          margin:0 auto;
          background: #FDD947;
          border-radius: 30px;
          color: #444;
          font-size: 20px;
          padding: 2px 30px;
          font-family: 'gilroy-extrabold';
          -webkit-transition-duration: 0.5s; /* Safari */
          transition-duration: 0.5s;
        }

        .btn:hover{
          text-align: center;
          border-radius: 30px;
          background-color: #444;
          color: #FDD947;
        }

        .regis{
          margin-top: 130px;
          color: #444;
        }

        #row{
          margin-top: 250px;
          color: #444;
        }

        .style13{
         height: 10px;
          border: 0;
          box-shadow: 0 10px 10px -10px #8c8b8b inset;
        }

        .form-control{
          border-radius: 90px;
          border-width: 2px;
        }

        .custom-select{
          border-radius: 90px;
        }

        @media (max-width:768px) {
          .logo1 {
            width: 150px;
          }
          .navbar {
            padding: 0;
          }

          li.some-text {
            display: none;
          }

          #row{
            margin-top: 0;
          }

          .reg{
            display: none;
          }

          .regis{
            margin-top: 80px;
          }
        }

        @media (min-width:760px) and (max-width:1200px) {
          .logo1 {
            width: 150px;
          }
          .navbar {
            padding: 0;
          }

          li.some-text {
            display: none;
          }

          #row{
            margin-top: 20%;
          }

          .regis{
            margin-top: 80px;
          }
        }
		
		.headlog{
		margin-left:620px;
		width:200px;
		height:70px;
		}

      </style>

</style>


 <div class="container" id="regist">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a href="#" class="navbar-brand"><img class="headlog" src="https://image.ibb.co/k4Zk3n/Asset_1.png" class="logo1"></a>
            </div>
          </div>
        </nav>

      </div>

home_all/templates/partials/header2.html
<style>
        body {
          background: #ecf0f1;  /* fallback for old browsers */
          font-size: 20px;
          margin-bottom: 100px;
        }
        ul.nav.navbar-nav .dropdown.open .dropdown-toggle{
          background-color: #206578;
        }

        nav{
          font-family: 'gilroy-extrabold';
        }

        @font-face {
          font-family: 'gilroy-light';
          src: url('gilroy-light.otf') format('opentype');
          font-weight: bold;
          font-style: bold;
        }

        @font-face {
          font-family: 'gilroy-extrabold';
          src: url('gilroy-extrabold.otf') format('opentype');
          font-weight: bold;
          font-style: bold;
        }

        .dropdown-menu > li > a:hover {
          background-color: #398DA3;
        }
        .navbar-nav>li>a {
          color: #444 !important;
          background: transparent;
          margin-bottom: 6px;
          top: 6px;
        }
        li.some-text {
          padding:12px 15px 5px 25px;
          font-size: 15px;
        }
        .navbar {
          background: #fff;  /* fallback for old browsers */
          box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);
          -moz-box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);
          -webkit-box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);

          border-radius: none;
          border: none;
          padding: 10px 100px;
        }
        .header {
          padding: 3px 10px;
        }
        li.button-login a{
          top: 2px;
        }
        .navbar-nav >li> a:hover {
          color: #444 !important;
          background: none;
        }
        .navbar-nav .dropdown li.active a {
          color: default;
          background-color: default;
          border-bottom: none;
        }
        .navbar-nav li.active a {
          color: #444 !important;
          background-color: transparent !important;
          border-bottom: 3px solid #ecf0f1;
        }
        .navbar-default .navbar-toggle .icon-bar {
          background-color: #444 !important;
        }
        .navbar-toggle{
          background: transparent;
          border: none;
          position: right;
        }
        .navbar-toggle:focus, .navbar-toggle:hover{
          background: rgba(236, 240, 241, 0.1) !important;
        }
        .logo1 {
          width: 150px;
        }
        li.some-text a {
          color: #77c9d4 !important;
          margin-bottom: 0;
          top: 0;
        }
        li.some-text {
          line-height: auto;
        }
        .btn-login {
          background: #FDD947;
          border-radius: 30px;
          color: #444;
          font-size: 20px;
          padding: 2px 30px;
          -webkit-transition-duration: 0.5s; /* Safari */
          transition-duration: 0.5s;
        }

        .btn-submit {
          display: block;
          margin:0 auto;
          background: #FDD947;
          border-radius: 30px;
          color: #444;
          font-size: 20px;
          padding: 2px 30px;
          font-family: 'gilroy-extrabold';
          -webkit-transition-duration: 0.5s; /* Safari */
          transition-duration: 0.5s;
        }

        .btn:hover{
          text-align: center;
          border-radius: 30px;
          background-color: #444;
          color: #FDD947;
        }

        .regis{
          margin-top: 130px;
          color: #444;
        }

        #row{
          margin-top: 250px;
          color: #444;
        }

        .style13{
         height: 10px;
          border: 0;
          box-shadow: 0 10px 10px -10px #8c8b8b inset;
        }

        .form-control{
          border-radius: 90px;
          border-width: 2px;
        }

        .custom-select{
          border-radius: 90px;
        }

        @media (max-width:768px) {
          .logo1 {
            width: 150px;
          }
          .navbar {
            padding: 0;
          }

          li.some-text {
            display: none;
          }

          #row{
            margin-top: 0;
          }

          .reg{
            display: none;
          }

          .regis{
            margin-top: 80px;
          }
        }

        @media (min-width:760px) and (max-width:1200px) {
          .logo1 {
            width: 150px;
          }
          .navbar {
            padding: 0;
          }

          li.some-text {
            display: none;
          }

          #row{
            margin-top: 20%;
          }

          .regis{
            margin-top: 80px;
          }
        }

      </style>

</style>


 <div class="container" id="regist">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a href="#" class="navbar-brand"><img src="https://image.ibb.co/k4Zk3n/Asset_1.png" class="logo1"></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav navbar-right">
                
				<li><a href="{% url 'home_all:index' %}" style="font-size: 20px"><strong>Lihat Beasiswa Anda</strong></a></li>
                <li><a href="#" style="font-size: 20px"><strong>Pengumuman</strong></a></li>
                <li class="button-login"><a href="{% url 'login:index' %}"><button class="btn btn-login"><b>Logout</b></button></a></li>
              </ul>
            </div>
          </div>
        </nav>

      </div>

home_all/templates/partials/header3.html
<head>
      <style>
        body {
          background: #ecf0f1;  /* fallback for old browsers */
          font-size: 20px;
          margin-bottom: 100px;
        }
        ul.nav.navbar-nav .dropdown.open .dropdown-toggle{
          background-color: #206578;
        }

        nav{
          font-family: 'gilroy-extrabold';
        }

        @font-face {
          font-family: 'gilroy-light';
          src: url('gilroy-light.otf') format('opentype');
          font-weight: bold;
          font-style: bold;
        }

        @font-face {
          font-family: 'gilroy-extrabold';
          src: url('gilroy-extrabold.otf') format('opentype');
          font-weight: bold;
          font-style: bold;
        }

        .dropdown-menu > li > a:hover {
          background-color: #398DA3;
        }
        .navbar-nav>li>a {
          color: #444 !important;
          background: transparent;
          margin-bottom: 6px;
          top: 6px;
        }
        li.some-text {
          padding:12px 15px 5px 25px;
          font-size: 15px;
        }
        .navbar {
          background: #fff;  /* fallback for old browsers */
          box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);
          -moz-box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);
          -webkit-box-shadow: 0px 0px 10px 10px rgba(119, 119, 119, 0.3);

          border-radius: none;
          border: none;
          padding: 10px 100px;
        }
        .header {
          padding: 3px 10px;
        }
        li.button-login a{
          top: 2px;
        }
        .navbar-nav >li> a:hover {
          color: #444 !important;
          background: none;
        }
        .navbar-nav .dropdown li.active a {
          color: default;
          background-color: default;
          border-bottom: none;
        }
        .navbar-nav li.active a {
          color: #444 !important;
          background-color: transparent !important;
          border-bottom: 3px solid #ecf0f1;
        }
        .navbar-default .navbar-toggle .icon-bar {
          background-color: #444 !important;
        }
        .navbar-toggle{
          background: transparent;
          border: none;
          position: right;
        }
        .navbar-toggle:focus, .navbar-toggle:hover{
          background: rgba(236, 240, 241, 0.1) !important;
        }
        .logo1 {
          width: 150px;
        }
        li.some-text a {
          color: #77c9d4 !important;
          margin-bottom: 0;
          top: 0;
        }
        li.some-text {
          line-height: auto;
        }
        .btn-login {
          background: #FDD947;
          border-radius: 30px;
          color: #444;
          font-size: 20px;
          padding: 2px 30px;
          -webkit-transition-duration: 0.5s; /* Safari */
          transition-duration: 0.5s;
        }

        .btn-submit {
          display: block;
          margin:0 auto;
          background: #FDD947;
          border-radius: 30px;
          color: #444;
          font-size: 20px;
          padding: 2px 30px;
          font-family: 'gilroy-extrabold';
          -webkit-transition-duration: 0.5s; /* Safari */
          transition-duration: 0.5s;
        }

        .btn-terima{
          background: #FDD947;
          border-radius: 30px;
          color: #444;
          font-size: 20px;
          -webkit-transition-duration: 0.5s; /* Safari */
          transition-duration: 0.5s;
        }

        .btn:hover{
          text-align: center;
          border-radius: 30px;
          background-color: #444;
          color: #FDD947;
        }

        .table-hover{
          border-radius: 15px;
        }

        .table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
          background-color: #FFF683;
        }

        td{
          border-top: none !important;
        }

        .regis{
          margin-top: 130px;
          color: #444;
        }

        #row{
          margin-top: 250px;
          color: #444;
        }

        .style13{
         height: 10px;
          border: 0;
          box-shadow: 0 10px 10px -10px #8c8b8b inset;
        }

        .form-control{
          border-radius: 90px;
          border-width: 2px;
        }

        .custom-select{
          border-radius: 90px;
        }

        a{
          color: #444;
        }

        a:hover{
          color: #FDD947;
        }

        #myCarousel{
          margin-bottom: 3%;
        }

        @media (max-width:768px) {
          .logo1 {
            width: 150px;
          }
          .navbar {
            padding: 0;
          }

          li.some-text {
            display: none;
          }

          #row{
            margin-top: 0;
          }

          .reg{
            display: none;
          }

          .regis{
            margin-top: 80px;
          }

           #myCarousel{
          display: none;
        }
        }

        @media (min-width:760px) and (max-width:1200px) {
          .logo1 {
            width: 150px;
          }
          .navbar {
            padding: 0;
          }

          li.some-text {
            display: none;
          }

          #row{
            margin-top: 20%;
          }

          .regis{
            margin-top: 80px;
          }
        }


      </style>
	  </head>

<header>
      <div class="container" id="regist">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a href="{% url 'list_pendaftar:index' %}" class="navbar-brand"><img src="https://image.ibb.co/k4Zk3n/Asset_1.png" class="logo1"></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'register_akun:index' %}" style="font-size: 20px"><strong>Daftar Beasiswa</strong></a></li>
                <li><a href="#" style="font-size: 20px"><strong>Pengumuman</strong></a></li>
                <li class="button-login"><a href="{% url 'login:index' %}"><button class="btn btn-login"><b>Logout</b></button></a></li>
              </ul>
            </div>
          </div>
        </nav>

      </div>

 </header>

home_all/templates/partials/headerbaru.html
<div class="myheader">
    <div class="container" id="regist">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand"><img class="headlog" src="https://image.ibb.co/k4Zk3n/Asset_1.png" class="logo1"></a>
                </div>
            </div>
        </nav>
    </div>
</div>